payly2/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.account import views as account
from apps.auth_service import views as auth
from apps.collaborator import views as collaborator
from apps.landing_page import views as landing_page
from apps.services import views as services

urlpatterns = [
    path('', landing_page.index, name='landing'),
    path('warranty/', landing_page.index, name='warranty'),  # TODO

    path('admin/', admin.site.urls, name='admin'),

    path('administrator/', include('apps.administrator.urls')),

    path('login/', auth.login_view, name='login'),
    path('logout/', auth.logout_view, name='logout'),
    path('forgot/', landing_page.index, name='forgot'),  # TODO
    path('register/', landing_page.index, name='register'),  # TODO

    path('services/', services.show_all_services, name='services'),
    path('pay', services.pay_service, name='service_pay'),

    path('account/', include([
        path('', account.home, name='account'),
        path('receipt/', account.receipts, name='account_receipts'),
    ])),

    path('collaborator/', include([
        # TODO create service menu for collaborator
        path('pay/', collaborator.pay_service_collaborator, name='collaborator_pay_service'),
        path('pay/<slug:service_id>', collaborator.pay_service_collaborator, name='collaborator_pay_service'),
        path('pay/<slug:service_id>/pay/', collaborator.process_order, name='collaborator_pay_service_pay'),
        path('receipts/', account.home, name='collaborator_receipts'),  # TODO
        path('due/', account.home, name='collaborator_due'),  # TODO
        path('payout/', account.home, name='collaborator_payout'),  # TODO
    ])),

    path('staff/payments', account.home, name='staff_payments'),  # TODO

    path('super/payments', account.home, name='super_payments'),  # TODO
    path('super/payout', account.home, name='super_payout'),  # TODO
]

apps/collaborator/models/collaborator_service_pay.py
from django.db import models

from apps.account.models import PaylyUser
from apps.services.models.service import Service


class Customer(models.Model):
    name = models.CharField('Nombre', max_length=100)
    whatsapp_number = models.CharField('Whatsapp', max_length=15)
    email = models.EmailField('Correo electrónico')


class CollaboratorServicePay(models.Model):
    collaborator = models.ManyToManyField(PaylyUser)
    service = models.ManyToManyField(Service)
    customer = models.ManyToManyField(Customer)
    amount = models.DecimalField('Monto del pago', decimal_places=2, max_digits=999)
    discount = models.FloatField('Descuento del pago')

apps/collaborator/forms/base_service_form.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField

PHONE_NUMBER_LENGTH = 10
MIN_AMOUNT_VALUE = 10
DECIMAL_PLACES = 2


class BaseServiceForm(forms.Form):
    client_whatsapp = PhoneNumberField(
        label='Whatsapp del cliente',
        region='MX',
        required=False,
    )
    service_discount = forms.CharField(
        widget=forms.HiddenInput(),
        required=False,
    )
    amount_to_pay = forms.DecimalField(
        label='Monto del recibo',
        min_value=MIN_AMOUNT_VALUE,
        decimal_places=DECIMAL_PLACES,
        required=True,
    )

apps/collaborator/forms/telmex_form.py
from phonenumber_field.formfields import PhoneNumberField

from apps.collaborator.forms.base_service_form import BaseServiceForm

PHONE_NUMBER_LENGTH = 10


class TelmexForm(BaseServiceForm):
    telmex_number = PhoneNumberField(
        label='Número Telmex del cliente',
        region='MX'
    )

    field_order = ['client_whatsapp', 'telmex_number', 'amount_to_pay']

collaborator/forms/telmex_form.py
from phonenumber_field.formfields import PhoneNumberField

from collaborator.forms.base_service_form import BaseServiceForm

PHONE_NUMBER_LENGTH = 10


class TelmexForm(BaseServiceForm):
    telmex_number = PhoneNumberField(
        label='Número Telmex del cliente',
        region='MX'
    )

    field_order = ['client_whatsapp', 'telmex_number', 'amount_to_pay']

apps/collaborator/views/pay_service.py
from django.shortcuts import redirect, render

from apps.collaborator.forms.telmex_form import TelmexForm
from apps.firebase_db.models.collections import Service

TITLE = 'Pagar '


def pay_service_collaborator(request, service_id=None):
    if not request.user.is_authenticated:
        return redirect('login')

    if not service_id:
        return redirect('services')

    service = Service().get_service(service_id=service_id)

    context = {
        'title': TITLE + service['name'],
        'id': service_id,
        'pay_form': TelmexForm(initial={
            'service_discount': 10,
        }),
        'service': service,
    }
    context['service']['service_id'] = service_id
    return render(
        request=request,
        template_name='collaborator/pay_service_base.html',
        context=context,
    )

apps/collaborator/views/process_order.py
from django.shortcuts import redirect

from apps.collaborator.forms.telmex_form import TelmexForm
from apps.firebase_db.models.collections import Service, Payment

TITLE = 'Pagar '


def process_order(request, service_id=None):
    if request.method == 'POST':
        requested_form = TelmexForm(request.POST)
        if requested_form.is_valid():
            print(requested_form)
            # Payment().collection.set({
            #     'user': userId,
            #     'user_ip': user_ip,
            #     'payment_date': datetime.now(),
            #     'payment_data': data,
            #     'payment_completed': False,
            #     'completed': False,
            #     'authorization': '',
            #     'problem': False,
            #     'discount': service_discount,
            #     'payment_method': 'Paypal'
            # })

    return redirect('account')

collaborator/views/pay_service.py
from django.shortcuts import redirect, render

from collaborator.forms.telmex_form import TelmexForm
from firebase_db.models.collections import Service

TITLE = 'Pagar '


def pay_service_collaborator(request, service_id=None):
    if not request.user.is_authenticated:
        return redirect('login')

    if not service_id:
        return redirect('services')

    service = Service().get_service(service_id=service_id)

    context = {
        'title': TITLE + service['name'],
        'id': service_id,
        'pay_form': TelmexForm(initial={
            'service_discount': 10,
        }),
        'service': service,
    }
    context['service']['service_id'] = service_id
    return render(
        request=request,
        template_name='collaborator/pay_service_base.html',
        context=context,
    )

collaborator/views/process_order.py
from django.shortcuts import redirect, render

from collaborator.forms.telmex_form import TelmexForm
from firebase_db.models.collections import Service, Payment

TITLE = 'Pagar '


def process_order(request, service_id=None):
    if request.method == 'POST':
        requested_form = TelmexForm(request.POST)
        if requested_form.is_valid():
            print(requested_form)
            # Payment().collection.set({
            #     'user': userId,
            #     'user_ip': user_ip,
            #     'payment_date': datetime.now(),
            #     'payment_data': data,
            #     'payment_completed': False,
            #     'completed': False,
            #     'authorization': '',
            #     'problem': False,
            #     'discount': service_discount,
            #     'payment_method': 'Paypal'
            # })

    return redirect('account')

templates/collaborator/pay_service_base.html
{% extends "services/base_services.html" %}
{% load static %}

{% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
            src="https://www.paypal.com/sdk/js?client-id=ASz6HjZ_zRhKc9VMgvuUdw700Rzi-Po9-FHd0iY7wAkE5Z_DQk9Iz11hppR0iJV0-6qhBKqOKztZbimr&currency=MXN&locale=es_MX"></script>

    <style>
        #preview {
            width: 100vw;
            display: flex;
            justify-content: center;
        }

        #right,
        #left {
            width: 30%;
            display: flex;
            flex-direction: column;
            padding: 10px 10px 60pt;
        }

        h1 {
            font-size: 50pt;
            margin: 0 0 20pt;
            color: black;
        }

        input[type="tel"],
        input[type="number"],
        input[type="text"] {
            font-size: 30pt;
            border: 0;
            outline: 0;
            border-bottom: 1px solid black;
            width: 53%;
            margin-bottom: 10px;
            background: transparent;
            padding: 5pt;
            box-sizing: border-box;
            font-weight: 600;
            letter-spacing: -0.06em;
        }

        input[type="submit"] {
            bottom: 0;
            padding: 5pt 12pt;
            text-align: center;
            font-size: 19pt;
            width: 70%;
            color: #ffffff;
            background-color: #000000;
            border: 0;
            font-weight: 400;
            border-radius: 2px;
        }

        #right {
            box-sizing: border-box;
            border-radius: 5pt;
            padding: 0 40pt;
            color: #B0B0B0;
            color: #464646;
            text-align: center;
            display: none;
            flex-direction: column;
            justify-content: space-between;
        }

        .center-element {
            width: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 50pt;
            flex-direction: column;
        }

        .row {
            width: 100%;
            padding: 0 30pt;
            margin: 0;
            display: flex;
            justify-content: space-between;
            box-sizing: border-box;
        }

        p {
            margin: 0;
        }

        h3 {
            font-size: 20pt;
            color: #000000;
            margin-bottom: 50pt;
        }

        @media (max-width: 600px) {

            #left,
            #right {
                width: 90%;
                text-align: center;
            }

            #right {
                padding: 0;
            }

            input[type="tel"],
            input[type="number"] {
                width: 76%;
                text-align: center;
            }

            input[type="number"] {
                margin: 0 auto;
            }

            #amount-input {
                width: 40%;
            }

            #preview {
                align-items: center;
                flex-direction: column;
            }
        }

        form {
            width: inherit;
            height: inherit;
            align-items: inherit;
            flex-direction: inherit;
        }

        label {
            font-size: 50pt;
            margin: 20pt 0 0;
            color: black;
            font-weight: bold;
        }

        label[for="id_amount_to_pay"],
        #id_amount_to_pay {
            display: none;
        }

        .hidden-input {
            display: none;
        }
    </style>
    <div id="preview">
        <form action="{% url 'collaborator_pay_service_pay' service.service_id %}" method="post">
            <div id="left">
                {% csrf_token %}
                {% for field in pay_form %}
                    {% if not field.is_hidden %}
                        <label id="label_{{ field.id_for_label }}"
                               for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% endif %}
                    {{ field }}
                {% endfor %}
            </div>
            <div id="right">
                <h3>Resumen de pago</h3>
                <div class="row">
                    <p>Monto del recibo {{ name }}</p>
                    <strong id="amount">$12345</strong>
                </div>
                {% if discount != 0 %}
                    <div class="row">
                        <p>Descuento Payly</p>
                        <strong id="discount">-$xxx</strong>
                    </div>
                {% endif %}
                <hr>
                <div class="row">
                    <p>Total a pagar</p>
                    <strong id="total">$12</strong>
                </div>
                <div class="center-element">
                    <input id="btnpagar" type="submit" value="Pagar" style="margin-bottom: 20px;">
                </div>
            </div>
        </form>
    </div>
    <script src="{% static '/js/collaborator/pay/telmex.js' %}"></script>
    <script>
        function post(path, params, method = 'post') {
            const form = document.createElement('form');
            form.method = method;
            form.action = path;

            for (const key in params) {
                if (params.hasOwnProperty(key)) {
                    const hiddenField = document.createElement('input');
                    hiddenField.type = 'hidden';
                    hiddenField.name = key;
                    hiddenField.value = params[key];
                    form.appendChild(hiddenField);
                }
            }
            document.body.appendChild(form);
            form.submit();
        }
    </script>

{% endblock %}